version: '3.8'  # Updated version for more features, if needed

services:
  web:
    build: ./app
    command: gunicorn gas_utility_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Load environment variables from .env file
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: {} 
