version: '3'

services:
  web:
    build: ./app
    command: gunicorn gas_utility_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Load environment variables from .env file

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/app/static  # Serve static files from /app/static
    depends_on:
      - web
